version: '3'

services:
  app:
    container_name: secim_apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    networks:
      - local-bridge
    tty: true

  db:
    container_name: secim_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - local-bridge
    tty: true

volumes:
  db_data:
    driver: local

networks:
  local-bridge:
    driver: bridge
